project:
  type: book
  output-dir: docs

lang: pt-br
engine: knitr

book:
  title: "Manual do IDE Positron"
  author: "Luís Gustavo Schuck"
  date: today
  sidebar:
    collapse-level: 1
  repo-url: https://github.com/lgschuck/positron_manual
  
  downloads: [pdf]

  page-footer:
      left: |
        Manual do IDE Positron
      right: |
        Material criado com software livre: R, Positron e Quarto.
      background: '#02556c'
  chapters:
    - index.qmd
    - autor.qmd
    - intro.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      light: [cosmo , tema.scss]
      dark: [slate]
  pdf:
    documentclass: scrreprt