project:
  type: book
  output-dir: docs

lang: pt

book:
  title: "Manual do IDE Positron"
  author: "Luís Gustavo Schuck"
  date: today
  sidebar:
    collapse-level: 1
  repo-url: https://github.com/lgschuck/positron
  
  downloads: [pdf]

  chapters:
    - index.qmd
    - intro.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



